name: "Checkout and Setup Gradle"
description: "Checks out repository, installs java, and restores gradle and build cache"

inputs:
  java_version:
    description: "Java version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Shallow Clone (--recurse-submodules)
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install JDK ${{ matrix.java }} (Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
    - name: Cache local .gradle and gradle packages
      uses: actions/cache@v1
      with:
        path: |
          ~/.gradle/caches
          .gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Cache build folders
      uses: actions/cache@v1
      with:
        path: "**/build"
        key: ${{ runner.os }}-build-${{ github.sha }}
