name: Public Release on Tag

on:
  push:
    tags:
      - 'release-'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true # Clone with vs-core submodule

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_curse_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
          ORG_GRADLE_PROJECT_curse_project_id: 651998
          ORG_GRADLE_PROJECT_CustomReleaseVersion: ${{ github.ref_name }}
        run: |
          ./gradlew build curseforge --stacktrace --no-daemon
