name: Public Release on Tag

on:
  push:
    tags:
      - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Shallow Clone (--recurse-submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Gradle & Caches
        uses: "./.github/actions/setup-gradle"

      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_curse_api_key: ${{ secrets.CURSEFORGE_API_KEY }}
          ORG_GRADLE_PROJECT_curse_project_id: 651998
          ORG_GRADLE_PROJECT_CustomReleaseVersion: ${{ github.ref_name }}
        run: |
          ./gradlew curseforge --stacktrace --no-daemon
